name: GitHub Actions Demo
on: [push, pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      # First ensure we've got babashka installed
      - run: curl -sLO https://raw.githubusercontent.com/babashka/babashka/master/install
      - run: chmod +x ./install
      - run: ./install
      # Then run the tests
      - run: bb run tests
      - name: Run Emacs tests for neil.el
        uses: purcell/setup-emacs@master
        with:
          version: 28.1
